### ISSUE TITLE
Instruction for configuring general velero chart

### ISSUE THREAD

**Issue by tareqhs** [AliyunContainerService/velero-plugin#16]
Hi,

I might be wrong but I've noticed that the helm chart provided with the plugin is basically a specially configured version of the general helm chart of velero that can be used for aws & azure:
https://github.com/helm/charts/tree/master/stable/velero

Maybe we should have instructions for configuring the general chart to work with the velero plugin instead of creating an incompatible fork? We maintain a multi-cloud deployment where we configure and install the same helm charts for several installations and velero is the only chart that is completely different between different providers instead of simply having different values.

**Comment by tareqhs** [comment]
I've got it to work. This is the required values.yaml override in the public chart:
```yaml
initContainers:
- image: registry.cn-hangzhou.aliyuncs.com/acs/velero-plugin-alibabacloud:v1.2
  name: velero-plugin-alibabacloud
  volumeMounts:
  - mountPath: /target
    name: plugins
configuration:
  provider: alibabacloud
  backupStorageLocation:
    name: alibabacloud
    bucket: <BUCKET>
  extraEnvVars:
    ALIBABA_CLOUD_ACCESS_KEY_ID: <KEY_ID>
    ALIBABA_CLOUD_ACCESS_KEY_SECRET: <KEY_SECRET>
    ALIBABA_CLOUD_OSS_ENDPOINT: <ENDPOINT>
credentials:
  useSecret: false
```
