### ISSUE TITLE
unsupported CSI driver: rook-ceph.rbd.csi.ceph.com

### ISSUE THREAD

**Issue by Hcreak** [AliyunContainerService/velero-plugin#41]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
**backup logs:**
level=error msg="Error attempting to get volume ID for persistent volume" backup=velero/production-backup error="rpc error: code = Unknown desc = unsupported CSI driver: rook-ceph.rbd.csi.ceph.com" error.file="/home/regressionTest/go/src/github.com/AliyunContainerService/velero-plugin/velero-plugin-for-alibabacloud/volume_snapshotter.go:264" error.function=main.checkCSIVolumeDriver group=v1 logSource="pkg/backup/item_backupper.go:438" name=pvc-8b09731c-a57f-47d2-98bf-cf98d90ba6bd namespace= persistentVolume=pvc-8b09731c-a57f-47d2-98bf-cf98d90ba6bd resource=persistentvolumes volumeSnapshotLocation=default

**What did you expect to happen:**
create backup

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version: (use `ark version`):  
   Client:
	Version: v1.5.2
    Server:
	Version: v1.2.0
- Kubernetes version: (use `kubectl version`):
   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", 
   Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", 
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1 LTS

**Comment by nikitakogan1** [comment]
Hi, i have the same issue when I use velero 1.5.2 with ali cloud. 
Client:
Version: v1.5.2
Server:
Version: v1.5.2

I am trying to create a backup and I get a log that is similar to what @Hcreak posted.
Can you please advise how to fix it?

Regards,
Nikita.

**Comment by yuvalman** [comment]
Hi,
This issue can be solved by adding the value snapshotVolumes: false to your schedule template in your values.yaml in velero chart.

For example:
```
schedules:
  mybackup:
    labels:
      myenv: foo
    annotations:
      myenv: foo
    schedule: "0 0 * * *"
    template:
      ttl: "240h"
      includedNamespaces:
      - foo
      **snapshotVolumes: false**
      
```
