### ISSUE TITLE
reading plugin stderr

### ISSUE THREAD

**Issue by kelvin-yue-scmp** [AliyunContainerService/velero-plugin#5]
**What steps did you take and what happened:**

An error shown during scheduled backup

```
time="2019-07-24T20:53:18Z" level=info msg="Checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:441"
time="2019-07-24T20:53:18Z" level=info msg="Done checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:469"
time="2019-07-24T21:01:25Z" level=info msg="Syncing contents of backup store into cluster" backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:170"
time="2019-07-24T21:01:25Z" level=info msg="Got backups from backup store" backupCount=20 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:178"
time="2019-07-24T21:04:25Z" level=error msg="reading plugin stderr" cmd=/plugins/velero-plugin controller=backup-sync error="read |0: file already closed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:89" pluginName=velero-plugin
time="2019-07-24T21:31:26Z" level=error msg="reading plugin stderr" cmd=/plugins/velero-plugin controller=backup-sync error="read |0: file already closed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:89" pluginName=velero-plugin
time="2019-07-24T21:34:26Z" level=error msg="reading plugin stderr" cmd=/plugins/velero-plugin controller=backup-sync error="read |0: file already closed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:89" pluginName=velero-plugin
```

**What did you expect to happen:**

Can backup successfully

**Environment:**

- Velero version: (use `ark version`):  v1.0.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-04-22T11:34:20Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: aliyun
- Cloud provider or hardware configuration: aliyun
- OS (e.g. from `/etc/os-release`): aliyun linux

**Comment by haoshuwei** [comment]
@kelvin-yue-scmp can you show me the command you used to make a scheduled backup?

**Comment by kelvin-yue-scmp** [comment]
We are using the Schedule CRD to do the backup
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: prod-2
  namespace: velero
spec:
  schedule: 0 20 * * *
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    storageLocation: ""
    ttl: 720h0m0s
    volumeSnapshotLocations: null
```
